- name: Move code to DUT
  hosts: uni_device
  tasks: 
    - name: Check if dir & code exist
      ansible.builtin.stat:
        path: ~/p4code
      register: p4dir_stat

    - name: Create dir if not exists
      ansible.builtin.file:
        path: ~/p4code
        state: directory
      when: not p4dir_stat.stat.exists

    - name: Copy code
      ansible.builtin.copy:
        src: /home/bebe/Desktop/Projects/p4s/{{ program }}/
        dest: ~/p4code/{{ program }}/

    - name: Check tools dir exists
      ansible.builtin.stat:
        path: ~/tools
      register: tools_stat

    - name: Copy tools dir if not exist
      ansible.builtin.copy:
        src: /home/bebe/Desktop/imslab/tools/
        dest: ~/tools/
      when: not tools_stat.stat.exists

    - name: chmod script
      ansible.builtin.file:
        path: ~/tools/p4_build.sh
        mode: '0755'
      when: not tools_stat.stat.exists

- name: Build code
  hosts: uni_device
  tasks:
    - name: Check program is Build or not
      ansible.builtin.stat:
        path: "$SDE/build/p4-build/tofino/{{ program }}"
      register: build_stat

    - name: Display build_stat
      ansible.builtin.debug:
        msg: "{{ build_stat }}"

    - name: Build code by tools/p4_build.sh
      ansible.builtin.shell: 'bash -c "sudo -E ~/tools/p4_build.sh ~/p4code/{{ program }}/p4src/{{ program }}.p4"'
      # when: not build_stat.stat.exists
        