- name: Build code
  hosts: topo_without_nchc
  tasks:
    - name: Build code by tools/p4_build.sh
      ansible.builtin.shell: 'bash -c "sudo -E ~/tools/p4_build.sh ~/p4code/{{ program }}/p4src/{{ program }}.p4"'