- name: operate tmux
  hosts: path1
  tasks:
    - name: check tmux session
      ansible.builtin.command: "tmux has-session -t p4"
      register: tmux_session_check
      ignore_errors: yes

    - name: tmux failed
      debug:
        msg: "No tmux session running"
      when: tmux_session_check.rc != 0

    - name: Create tmux session 'p4' if it does not exist
      ansible.builtin.command: tmux new-session -d -s p4
      when: tmux_session_check.rc != 0

    - name: Clear session pane
      ansible.builtin.command: tmux send-keys -t p4 'clear' C-m

    - name: run switchd 
      ansible.builtin.command: tmux send-keys -t p4 '$SDE/run_switchd.sh -p lab1_port' C-m

    - name: Wait for a moment to ensure bf_shell UP
      pause:
        seconds: 15
    
    - name: operate SDE through tmux
      block: 
      - name: ucli
        ansible.builtin.command: tmux send-keys -t p4 'ucli' C-m

      - name: Show qsfp
        ansible.builtin.command: tmux send-keys -t p4 'qsfp show' C-m

      - name: Capture output from tmux session 'p4'
        ansible.builtin.command: tmux capture-pane -pt p4
        register: tmux_capture_output
        when: tmux_session_check.rc == 0

      - name: Display output from tmux session 'p4'
        debug:
          msg: "{{ tmux_capture_output }}"
        when: tmux_session_check.rc == 0

      always:
      - name: Quit switchd
        ansible.builtin.command: tmux send-keys -t p4 C-\\ C-m

    - name: Clear session pane
      ansible.builtin.command: tmux send-keys -t p4 'clear' C-m
      when: tmux_session_check.rc == 0