- name: operate tmux
  hosts: test_uni_device
  become: yes
  become_user: nckutest
  tasks:

    - name: Iterate over the list in host_vars
      ansible.builtin.debug:
        msg: " {PORT SPEED} : {{ item['port'] }} {{ item['dp'] }}: {{ item['speed'] }}"
      with_items: " {{ ports }} "


