- name: operate tmux
  hosts: topo
  tasks:
    # - name: Link kernel header
    #   ansible.builtin.command: ln -s /usr/share/onl/packages/amd64/onl-kernel-4.14-lts-x86-64-all/mbuilds/ /lib/modules/4.14.151-OpenNetworkLinux/build

    - name: Load driver
      ansible.builtin.command: bf_kdrv_mod_load $SDE_INSTALL
      ignore_errors: yes
      
    - name: check tmux session
      ansible.builtin.command: "tmux has-session -t p4"
      register: tmux_session_check
      ignore_errors: yes

    - name: tmux failed
      debug:
        msg: "No tmux session running"
      when: tmux_session_check.rc != 0

    - name: Create tmux session 'p4' if it does not exist
      ansible.builtin.command: tmux new-session -d -s p4
      when: tmux_session_check.rc != 0

    - name: Clear session pane
      ansible.builtin.command: tmux send-keys -t p4 'clear' C-m